server.port=8081
spring.application.name=erpsoftware

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/erp_software;INIT=CREATE SCHEMA IF NOT EXISTS erp;AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.default_schema=erp

spring.security.user.name=beena
spring.security.user.password=Beena@123

# Disable Thymeleaf cache for immediate template updates
spring.thymeleaf.cache=false

